### PR TITLE
benchmarks in parallel

### PR DESCRIPTION
**Pull request by daveads**
/claim #318

### CODE REVIEW

**Comment by tusharmath** [comment]
@daveads Thanks! The idea was to run them in separate environments and not in parallel on the same runner. Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

**Comment by daveads** [comment]
@tusharmath  Can i make each service run its own Docker container

**Comment by daveads** [comment]
@tusharmath  Discord invite Expired.

**Comment by daveads** [comment]
@tusharmath ready for review

**Comment by daveads** [comment]
The Graphql sever now runs separate environments...

**Comment by tusharmath** [comment]
Thanks @daveads but I don't think this is going in the right direction.

1. It should have used a GH matrix to run the jobs in parallel
2. Current benchmarks are all wrong, every is performing almost similarly.

For the above reasons I am closing this PR.

**Pull request closed without merging**
